#!/usr/bin/env bash

# is the internet on fire status reports, if we have network

message_dir="/tmp/messages"
mkdir -p "$message_dir"
sudo chown "$(whoami)" "$message_dir"

# set to seconds since epoch
seconds_since_epoch=$(date +%s)
message_file="$message_dir/$seconds_since_epoch"

message=$(host -W1 -t txt istheinternetonfire.com | cut -f 2 -d '"') || "Could not get txt record of istheinternetonfire.com"

echo "$message" > "$message_file"
