#!/bin/sh

proxy_path="/etc/proxy"
if [ -e "$proxy_path" ]; then
  proxy=$(cat $proxy_path)
  curl --proxy "$proxy" -sL icanhazip.com -o /tmp/external-ip
else
  curl -sL icanhazip.com -o /tmp/external-ip
fi
