---
keys:
  # user keys
  - &kyle 3C799D26057B64E6D907B0ACDB0E3C33491F91C9 # yubikey

  # machine keys
  - &cogsworth age1am5p2xzksgsh93zgnznfp3rxpn69wexql9nyjl4ng7qeu386qvjq3pk2vy
  - &dino age1t0eyg4vswkrry0ff0uzrfflyfmxkzctz9ngay7k2z0k3mgt9t9zqm7z0sn
  - &elk age1t6aj3v8j6ecehdpr978x4hgu5u9y98gtkw47scyzhfssnzrvs9ssye2tst

  # command to add a new age key for a new host
  # nix-shell -p ssh-to-age --run "ssh-keyscan $host | ssh-to-age"
  # sops -r updatekeys ./nix/secrets/secrets.yaml
creation_rules:
  - path_regex: nix/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cogsworth
          - *dino
          - *elk
        pgp:
          - *kyle
  - path_regex: nix/hosts/cogsworth/keys/.*\.sops$
    key_groups:
      - age:
          - *cogsworth
          - *dino
        pgp:
          - *kyle
