---
keys:
  # user keys
  - &kyle 3C799D26057B64E6D907B0ACDB0E3C33491F91C9 # yubikey

  # machine keys
  - &alpha age1k0jtatca72hz5ayecaa20pzqn6g6rf0c2ph3m0qzkq0cq05dfflsay2jpl
  - &cheetah age1hp8z0w03ulmygen56q0nl9mtu02979tgrc3vfy5r32r3pn4dxvyqtnnywd
  - &dino age1t0eyg4vswkrry0ff0uzrfflyfmxkzctz9ngay7k2z0k3mgt9t9zqm7z0sn
  - &tiger age1mcse3suy7qxr7pxn262zw67lrz2wyl8pr6hgqs5x0fk5p0w7qa4s9lnctc

  # command to add a new age key for a new host
  # nix-shell -p ssh-to-age --run "ssh-keyscan $host | ssh-to-age"
  # sops -r updatekeys ./nix/secrets/secrets.yaml
creation_rules:
  - path_regex: nix/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *alpha
          - *cheetah
          - *dino
          - *tiger
        pgp:
          - *kyle
