{
 "title": "NGINX Log Metrics [M]",
 "description": "NGINX Log metrics with Prometheus based on https://github.com/martin-helmich/prometheus-nginxlog-exporter \r\nBased on namespace prefix 'nginx'. If different, you may need to adjust the metrics.\r\nDashboard based on 6482 dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host:",
    "query": {
     "query": "label_values(nginx_http_response_count_total,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Percentage Ratio of status codes to all status codes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"^2..\",host=\"$host\"}[1m])) / sum(rate(nginx_http_response_count_total{host=\"$host\"}[1m])) * 100",
     "legendFormat": "2** status codes"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"^4..\",host=\"$host\"}[1m])) / sum(rate(nginx_http_response_count_total{host=\"$host\"}[1m])) * 100",
     "legendFormat": "4** status codes"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"^5..\",host=\"$host\"}[1m])) / sum(rate(nginx_http_response_count_total{host=\"$host\"}[1m])) * 100",
     "legendFormat": "5** status codes"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_time_seconds_count{host=\"$host\"}[1m])) ",
     "legendFormat": "$host"
    }
   ]
  },
  {
   "title": "HTTP Traffic",
   "type": "graph",
   "description": "Response sizes in bytes",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_size_bytes{host=\"$host\"}[5m])) ",
     "legendFormat": "$host"
    }
   ]
  },
  {
   "title": "Average Response Time [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_time_seconds_sum{host=\"$host\"}[5m])) / sum(rate(nginx_http_response_time_seconds_count{host=\"$host\"}[5m])) ",
     "legendFormat": "$host"
    }
   ]
  },
  {
   "title": "Status codes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{host=\"$host\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Response time (90% quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_response_time_seconds{quantile=\"0.9\",method=\"GET\",status=~\"2[0-9]*\",instance=~\"$host\"}",
     "legendFormat": "$host"
    }
   ]
  }
 ]
}