# Hardware description for pika, an ODROID-H2 (quad-core Celeron J4105,
# 32GB DDR4, 500GB NVMe, two SATA3 ports).
#
# NOT generated by nixos-generate-config on this machine. It is w1's config,
# recovered from the commit that retired the three H2 boards:
#
#   git show 58aed155^:nix/hosts/w1/hardware-configuration.nix
#
# The boards are identical, so this is accurate, but regenerate it on the
# real hardware before trusting it:
#
#   nixos-generate-config --no-filesystems --root /mnt
#
# and reconcile any difference rather than overwriting this file, since the
# filesystem entries below are deliberate and nixos-generate-config would
# emit UUIDs instead of labels.

{
  lib,
  config,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd.availableKernelModules = [
      "ahci" # both SATA ports, and what passes SMART through to smartd
      "xhci_pci"
      "nvme" # root
      "usb_storage"
      "usbhid"
      "sd_mod"
      "sdhci_pci"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  # Labels, not UUIDs. The partitions are created by hand once (see the
  # provisioning block in configuration.nix) and a label survives having to
  # recreate one of them on a spare board without editing this file.
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };
  };

  swapDevices = [ ];

  # Two onboard NICs, enp2s0 and enp3s0. Only one is cabled; DHCP on both is
  # harmless and means it does not matter which port gets used.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
