{
  config,
  lib,
  pkgs,
  ...
}:
with lib;
let
  cfg = config.hmFoundry.desktop.input.hammerspoon;

  # Default app bindings: Cmd+Alt + key -> app bundle ID
  defaultAppBindings = {
    j = "org.alacritty";
    k = "org.nixos.firefox"; # Home Manager Firefox uses org.nixos.firefox
    h = "com.tinyspeck.slackmacgap";
    u = "notion.id";
    n = "com.spotify.client";
    i = "com.linear";
    y = "us.zoom.xos";
  };

  # Merge user-provided bindings with defaults
  appBindings = defaultAppBindings // cfg.appBindings;

  # Generate Lua code for app switching hotkeys
  appSwitchingCode = concatStringsSep "\n" (
    mapAttrsToList (key: bundleId: ''
      hs.hotkey.bind({"cmd", "alt"}, "${key}", function()
        hs.application.launchOrFocusByBundleID("${bundleId}")
      end)
    '') appBindings
  );

  # Generate the complete Hammerspoon init.lua
  hammerspoonConfig = ''
    -- Hammerspoon configuration
    -- Generated by NixOS home-manager
    -- Do not edit manually - changes will be overwritten

    ${optionalString cfg.showAlert ''
      -- Show notification on successful load
      hs.notify.new({title="Hammerspoon", informativeText="Configuration loaded"}):send()
    ''}

    ${optionalString cfg.autoReload ''
      -- Auto-reload configuration when files change
      function reloadConfig(files)
        local doReload = false
        for _, file in pairs(files) do
          if file:sub(-4) == ".lua" then
            doReload = true
          end
        end
        if doReload then
          hs.reload()
        end
      end
      configWatcher = hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", reloadConfig):start()
    ''}

    -- Application quick-switch hotkeys (Cmd+Alt+Key)
    ${appSwitchingCode}

    ${cfg.extraConfig}
  '';
in
{
  options.hmFoundry.desktop.input.hammerspoon = {
    enable = mkEnableOption "Hammerspoon window management and automation";

    appBindings = mkOption {
      type = types.attrsOf types.str;
      default = { };
      example = {
        j = "org.alacritty";
        k = "org.mozilla.firefox";
      };
      description = ''
        App bundle ID bindings for quick-switch hotkeys.
        Maps key (under Cmd+Alt) to app bundle ID.
        Merges with defaults: j=Alacritty, k=Firefox, h=Slack, u=Notion, n=Spotify, i=Linear, y=Zoom
      '';
    };

    autoReload = mkOption {
      type = types.bool;
      default = true;
      description = "Automatically reload Hammerspoon when configuration changes";
    };

    showAlert = mkOption {
      type = types.bool;
      default = true;
      description = "Show notification when Hammerspoon configuration loads";
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      example = ''
        -- Custom Hammerspoon code
        hs.window.animationDuration = 0
      '';
      description = "Additional Lua code to inject into init.lua";
    };
  };

  config = mkIf (pkgs.stdenv.isDarwin && cfg.enable) {
    # Generate ~/.hammerspoon/init.lua
    home.file.".hammerspoon/init.lua" = {
      text = hammerspoonConfig;
      force = true;
    };

    # Note: Hammerspoon itself should be installed via Homebrew
    # Add "hammerspoon" to homebrew.casks in nix-darwin configuration
  };
}
