#!/usr/bin/env bash

secure() {
  local arg

  for arg; do
    if [ -d "$arg" ]; then
      chmod 700 "$arg"
    elif [ -f "$arg" ]; then
      chmod 600 "$arg"
    fi
  done
}

pull_or_update() {
  local repo=$1
  local destination=$2

  if [ ! -d "$destination" ]; then
    mkdir -p "$(dirname "$destination")"
    git clone https://github.com/"$repo" "$destination"
  else
    git -C "$destination" pull
  fi
}

# Antigen. Zsh package maneger
echo "Updating antigen"
pull_or_update "zsh-users/antigen" "$HOME/.config/zsh/antigen"

# Ruby Env
#RBENV="$HOME/.rbenv"
#echo "Updating rbenv"
#pull_or_update "rbenv/rbenv" "$RBENV"
#(cd "$RBENV" && src/configure && make -C src) || true
#echo "Updating ruby-build plugin"
#pull_or_update "rbenv/ruby-build" "$RBENV/plugins/ruby-build"

# z
echo "Updating z"
pull_or_update "rupa/z/" "$HOME/.src/z"

# tmux plugin manager
echo "Updating TMux Plugin Manager"
pull_or_update "tmux-plugins/tpm" "$HOME/.tmux/plugins/tpm"

# pyenv
echo "Updating pyenv"
pull_or_update "pyenv/pyenv.git" "$HOME/.pyenv"

# pyenv-virtualenv
echo "Updating pyenv-virtualenv"
pull_or_update "pyenv/pyenv-virtualenv" "$(pyenv root)/plugins/pyenv-virtualenv"

secure ~/.msmtprc ~/.config/gnupg

[ -d ~/.mutt ] && mkdir -p ~/.mutt/temp
