#!/usr/bin/env bash

secure() {
  local arg

  for arg; do
    if [ -d "$arg" ]; then
      chmod 700 "$arg"
    elif [ -f "$arg" ]; then
      chmod 600 "$arg"
    fi
  done
}

secure ~/.msmtprc ~/.config/gnupg

[ -d ~/.mutt ] && mkdir -p ~/.mutt/temp

# dot-prefixed files are skipped unless explicitly named
rcup -K config/zsh/{.zprofile,.zshenv,.zshrc}
