package flux

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/kyleondy/dotfiles/forge/internal/state"
	"github.com/kyleondy/dotfiles/forge/internal/ticket"
	"github.com/kyleondy/dotfiles/forge/internal/ui"
)

const specTemplate = `<!--
SPEC for %s. Generated by ` + "`forge flux init`" + `; populate with ` + "`forge flux spec`" + `.

Six required sections (the spec phase enforces them):
  1. Outcomes
  2. In scope
  3. Out of scope
  4. Constraints & assumptions
  5. Prior decisions
  6. Verification criteria
-->
`

const decisionsTemplate = `# Architectural decisions for %s

Append-only. One line per decision. Format:

YYYY-MM-DD <decision summary>

`

func newInitReal() *cobra.Command {
	return &cobra.Command{
		Use:               "init <ticket>",
		Short:             "Scaffold the on-disk layout for a ticket",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: completeTicketIDs,
		RunE: func(_ *cobra.Command, args []string) error {
			id := args[0]
			cfg, l, err := requireTicket(id, true)
			if err != nil {
				return err
			}
			if err := writeTemplateIfMissing(l.SpecPath, fmt.Sprintf(specTemplate, id)); err != nil {
				return err
			}
			if err := writeTemplateIfMissing(l.DecPath, fmt.Sprintf(decisionsTemplate, id)); err != nil {
				return err
			}
			// Initialize state.json so subsequent reads succeed.
			s, err := state.Load(l, id)
			if err != nil {
				return err
			}
			if err := state.Save(l, s); err != nil {
				return err
			}
			log := ui.L()
			log.Info("ticket dir: %s", l.Root)
			if ticket.IsLinear(id) {
				log.Info("next: forge flux linear fetch %s  # pull Linear context", id)
			} else {
				log.Info("next: forge flux spec %s \"<freeform description>\"", id)
			}
			_ = cfg
			return nil
		},
	}
}

func writeTemplateIfMissing(path, body string) error {
	if _, err := os.Stat(path); err == nil {
		ui.L().Info("exists: %s", path)
		return nil
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	ui.L().Info("wrote %s", path)
	return nil
}
