#!/usr/bin/env bash
set -e

# logs weight to intervals.icu

usage() {
  echo "$0 <weight_in_lb>"
}

if [[ $# -ne 1 ]]; then
  useage
fi

# The API seems to require the weight to be in KG
kg=$(echo "scale=1 ; $1 / 2.20462" | bc)

 curl \
   -X PUT \
   -u "API_KEY:$(pass show intervals.icu/api)" \
   -H 'Content-Type: application/json' \
   -d "{ \"weight\": $kg }" \
    "https://intervals.icu/api/v1/athlete/i10991/wellness/$(date +%Y-%m-%d)"

