#!/usr/bin/env bash

die() {
  echo "some error has occurred?"
  exit 1
}

add_newline() {
  echo >>"$NOTES_FILE"
}

add_date() {
  # inset the date as an H2
  echo "## $(date)" >>"$NOTES_FILE"
}

# in cases where you may want to store notes somewhere you can version control
# them, or some sync-ed storage
NOTES_FILE=${NOTES_FILE:-$HOME/notes.md}
cd "$(dirname "$NOTES_FILE")" || die

add_newline
add_date
add_newline

# here is some hacky control flow to bail here if I am opening this file from
# within vim
if [[ $1 == "--vim" ]]; then
  # to give us the newline between the date header and content
  add_newline
  echo "$NOTES_FILE"
  exit 0
fi

# check to see if data is being piped in
if [ -p /dev/stdin ]; then
  while IFS= read -r line; do
    echo "$line" >>"$NOTES_FILE"
  done
else
  if [[ $# -ne 0 ]]; then
    echo "$@" >>"$NOTES_FILE"
  fi
  $EDITOR "+normal Go" +startinsert "$NOTES_FILE"
fi
