#!/usr/bin/env bash

die() {
  echo "some error has occurred?"
  exit 1
}

add_newline() {
  echo >>"$NOTES_FILE"
}

# in cases where you may want to store notes somewhere you can version control
# them, or some sync-ed storage
NOTES_FILE=${NOTES_FILE:-$HOME/notes.md}
cd "$(dirname "$NOTES_FILE")" || die

add_newline
# inset the date as an H2
echo "## $(date)" >>"$NOTES_FILE"
add_newline

# check to see if data is being piped in
if [ -p /dev/stdin ]; then
  while IFS= read -r line; do
    echo "$line" >>"$NOTES_FILE"
  done

else

  if [[ $# -ne 0 ]]; then
    echo "$@" >>"$NOTES_FILE"
  fi
  $EDITOR "+normal Go" +startinsert "$NOTES_FILE"
fi
