#!/usr/bin/env bash
set -e

_log() {
  echo "==> $*"
}

gh_dir="$HOME/github.com"

gh_token="$(pass show github.com/tokens/grata_short)"
_log "Getting repos from API"
repo_info="$(github_api "$gh_token" /orgs/grataio/repos | jq -r '.[].ssh_url')"

mkdir -p "$gh_dir"
for repo in $repo_info; do
  # making some assumptions
  repo_name="$(echo "$repo" | cut -d'/' -f2 | cut -d'.' -f1)"
  #echo "$repo"
  #echo "$repo_name"

  repo_path="${gh_dir}/${repo_name}"
  if [ -d "$repo_path" ]; then
    _log "Updading $repo_name"
    git -C "$repo_path" fetch --all --prune --quiet || true
    git -C "$repo_path" rebase --rebase-merges --autostash --quiet || true
  else
    _log "Cloning $repo_name"
    git clone -- "$repo" "$repo_path"
  fi
done
