#!/usr/bin/env bash

media_dir=/mnt/media/yt
temp_dir="${HOME}/.yt-dl/downloads"


# remove watched episodes. this will remove anything that has been started.
echo "==> REMOVING THE FOLLOWING"
cnt=0
while IFS= read -r -d $'\0' file; do
  if [[ -f "$file" ]]; then
    rm -v "$file"
  fi
  ((cnt++))
done < <(journalctl --since="-7 days" -u jellyfin.service | rg --null-data --only-matching --replace='$1' 'file:"(/mnt/media/yt.*?)" -threads')
echo "==> DONE REMOVING"
echo "${cnt} vidoes watched in the last 7 days"

# Download new videos
yt-sync

# move into jellyfin dir
if [[ -z $(ls -A "${temp_dir}"/* 2>/dev/null) ]]; then
  echo "No downloads"
else
  rsync -aPh --remove-source-files "${temp_dir}"/* "$media_dir"
fi

# remove leftovers from incomplete downloads
fd \
  --extension=part \
  --extension="temp.webm" \
  --extension=meta \
  --extension=en.vtt \
  . /mnt/media/yt -x rm
fd --type=f 'f[0-9]+\.webm' /mnt/media/yt -x rm

# remove empty dirs
fd --type=empty --type=directory . "$media_dir" "$temp_dir" -x rmdir

# TODO: start sync of jellyfin media library
# curl -v -X GET -H "X-MediaBrowser-Token: TOKEN" https://jellyfin.tld/library/refresh

# print most recent videos and count of all videos
vids=$(fd --type=f . /mnt/media/yt -x echo '{/}' | sort)
if [[ $(echo "$vids" | wc -l) -le 21 ]]; then
  echo "$vids"
else
  echo "$vids" | head
  echo "..."
  echo "$vids" | tail
fi
echo "total videos: $(echo "$vids" | wc -l)"


