self: super: {
  ask = super.callPackage ./ask { };
  audio-language-check = super.callPackage ./audio-language-check { };
  babashka-scripts = super.callPackage ./babashka-scripts { };
  backup-photos = super.callPackage ./backup-photos { };
  backup-resolve-projects = super.callPackage ./backup-resolve-projects { };
  berkeley-mono = super.callPackage ./berkeley-mono { };
  berkeley-mono-nerd-font = super.callPackage ./berkeley-mono-nerd-font { };
  birdnet-go = super.callPackage ./birdnet-go { };
  forge = super.callPackage ./forge { lima = self.master.lima; };
  fuji-transcode = super.callPackage ./fuji-transcode { };
  git-worktree-prompt = super.callPackage ./git-worktree-prompt { };
  helios = super.callPackage ./helios { };
  histdb-backup = super.callPackage ./histdb-backup { };
  instax-link = super.callPackage ./instax-link { };
  kagi = super.callPackage ./kagi { };
  linear-cli = super.callPackage ./linear-cli { };
  my-scripts = super.callPackage ./my-scripts { };
  photos-fanout = super.callPackage ./photos-fanout { };
  photos-promote = super.callPackage ./photos-promote { };
  photos-recall = super.callPackage ./photos-recall { };
  pragmata-pro = super.callPackage ./pragmata-pro { };
  s3-archive-push = super.callPackage ./s3-archive-push { };
  s3-archive-reconcile = super.callPackage ./s3-archive-reconcile { };
  winnow = super.callPackage ./winnow { };
  kubectl-rexec = super.callPackage ./kubectl-rexec { };
  presence-debug = super.callPackage ./presence-debug { };
  pi-wrapper = super.callPackage ./pi-wrapper { inherit (self) llm-agents; };
  mcloud-pins = super.callPackage ./mcloud-pins { };
  search-mail = super.callPackage ./search-mail { };
  mlx = super.callPackage ./mlx { };
  tmux-status = super.callPackage ./tmux-status { };
}
